/**
 * 단어카드 한글 뜻 사전 (ADR-0065 Amendment #3 · E-2c 트랙).
 *
 * 카드 뒤집기 면에 표시할 **단어 → 한글 뜻 1개** 정적 사전이다.
 * 외부 사전 API를 쓰지 않는다 — 워커가 직접 작성했고 팀장 육안 검수를 거친다
 * (Hard Rule 11: PLAN.md 미명시 라이브러리 금지. 런타임 외부 호출도 0건).
 *
 * ── 대상 ────────────────────────────────────────────────────────────────────
 * 카드가 되는 고유 단어 **1,741개 전량**. 목록의 정본은 드라이런 산출물
 * `scripts/wordplay/out/wordplay-dryrun-20260821.json` 의 `w0.unique_words`이며,
 * 카드 표시 제외 167종(`card-excluded.ts`)은 애초에 여기 오지 않는다.
 * 목록과의 일치는 `scripts/wordcard_pilot/verify_ko_meanings.mjs`가 전수 대조한다.
 *
 * ── 표기 규칙 (표본 150개 검수 통과 기준을 그대로 승계) ─────────────────────
 *   1. 단어당 뜻 **1개**. 여러 뜻을 나열하지 않는다.
 *   2. 만 3~7세 눈높이. 가장 쉽고 일상적인 뜻을 고른다.
 *   3. **한글과 공백만** 쓴다. 한자·로마자·괄호·물결표 금지.
 *   4. **8자 이내**(공백 포함). 카드 UI 공간 제약이다.
 *   5. 품사 표기 없음.
 *   6. 다의어는 **실린 책 문맥**으로 판정한다(드라이런 JSON의 `books[].cards`로
 *      어느 책에 실렸는지 확인). 예: `charge`는 Knight Times → "돌진하다",
 *      `trunk`는 What Is It? → "코끼리 코".
 *
 * ── 승계분 ──────────────────────────────────────────────────────────────────
 * 이 중 **139개**는 E-2c-1 표본 150개 중 팀장 검수를 통과한 것을 **한 글자도 바꾸지
 * 않고** 옮겼다(표본 150 − 이후 제외 확정 11종). 원본은
 * `scripts/wordcard_pilot/out/sample_150_ko.tsv` 이고, 동일성은 검증 스크립트가 대조한다.
 *
 * ── 이 파일이 lib/ 에 있는 이유 ─────────────────────────────────────────────
 * 손으로 쓴 데이터라 유실되면 복구 비용이 크다. 스크립트 하위의 `out/` 디렉터리는
 * .gitignore 전역 규칙에 걸려 추적되지 않으므로 산출물 경로에 두지 않는다
 * (표본 150개 때와 같은 구조).
 *
 * ※ 이 주석 안에 별표와 빗금이 붙은 glob 패턴을 쓰지 말 것 — 블록 주석이 그 자리에서
 *   끝나 파일 전체가 깨진다(2026-08-21에 실제로 밟았다).
 *
 * ※ /wordplay 화면 연결은 이 파일의 범위가 아니다 — 사전까지만이다.
 */

/** 단어(정규형 소문자) → 한글 뜻. 키는 `select-words.ts`의 `normalizeWord` 결과와 같다. */
export const KO_MEANINGS: Readonly<Record<string, string>> = {
  // ── a ──
  'academic': '공부하는',
  'acid': '시큼한 물',
  'across': '건너서',
  'add': '더하다',
  'adding': '더하기',
  'adds': '더한다',
  'adults': '어른들',
  'adventure': '모험',
  'adventures': '모험',
  'advice': '도움말',
  'afraid': '무서운',
  'agent': '요원',
  'ago': '예전에',
  'agreed': '동의했다',
  'ahead': '앞으로',
  'air': '공기',
  'airplane': '비행기',
  'alien': '외계인',
  'allow': '허락하다',
  'alone': '혼자',
  'along': '따라서',
  'already': '벌써',
  'angrier': '더 화난',
  'angrily': '화나서',
  'angry': '화난',
  'animal': '동물',
  'animals': '동물들',
  'answer': '대답',
  'answered': '대답했다',
  'answers': '대답들',
  'ant': '개미',
  'ants': '개미들',
  'anything': '무엇이든',
  'anywhere': '어디든',
  'ape': '유인원',
  'appear': '나타나다',
  'apple': '사과',
  'apples': '사과들',
  "aren't": '아니다',
  'arguing': '다투는',
  'arm': '팔',
  'arms': '두 팔',
  'army': '군대',
  'aroma': '좋은 냄새',
  'around': '둘레에',
  'arrows': '화살들',
  'ashes': '재',
  'ask': '묻다',
  'asked': '물었다',
  'asking': '묻는',
  'asks': '묻는다',
  'ate': '먹었다',
  'atmosphere': '공기층',
  'attack': '공격하다',
  'attitude': '태도',
  'aunt': '이모',
  'authority': '권한',
  'away': '멀리',
  // ── b ──
  'babies': '아기들',
  'baboon': '개코원숭이',
  'baboons': '개코원숭이들',
  'baby': '아기',
  'back': '뒤',
  'bad': '나쁜',
  'bade': '인사했다',
  'bag': '가방',
  'bags': '가방들',
  'bajaj': '삼륜 택시',
  'bake': '굽다',
  'ball': '공',
  'ballet': '발레',
  'balloon': '풍선',
  'banana': '바나나',
  'bananas': '바나나들',
  'banquet': '잔치',
  'barn': '헛간',
  'basin': '대야',
  'basket': '바구니',
  'bat': '박쥐',
  'bath': '목욕',
  'bathtime': '목욕 시간',
  'bazaar': '시장',
  'beach': '바닷가',
  'beak': '부리',
  'beans': '콩',
  'bear': '곰',
  'beast': '짐승',
  'beautiful': '아름다운',
  'became': '되었다',
  'become': '되다',
  'becoming': '되어가는',
  'bed': '침대',
  'bees': '벌들',
  'beetle': '딱정벌레',
  'began': '시작했다',
  'begins': '시작한다',
  'begun': '시작된',
  'behave': '행동하다',
  'behind': '뒤에',
  'believe': '믿다',
  'bell': '종',
  'belly': '배',
  'belong': '속하다',
  'belt': '허리띠',
  'bendy': '잘 휘는',
  'berries': '산딸기들',
  'berry': '산딸기',
  'best': '가장 좋은',
  'better': '더 좋은',
  'bicycle': '자전거',
  'big': '큰',
  'bigger': '더 큰',
  'biggest': '가장 큰',
  'bike': '자전거',
  'bin': '쓰레기통',
  'bird': '새',
  'birds': '새들',
  'birdy': '새 같은',
  'birth': '탄생',
  'birthday': '생일',
  'biscuit': '과자',
  'black': '까만',
  'blankie': '애착 담요',
  'blind': '눈이 안 보이는',
  'bling': '반짝이 장식',
  'blonde': '금발의',
  'blow': '불다',
  'blowing': '부는',
  'blue': '파란',
  'board': '판',
  'boastful': '잘난 척하는',
  'boat': '나룻배',
  'body': '몸',
  'boiled': '삶았다',
  'boiling': '끓는',
  'bold': '용감한',
  'bones': '뼈들',
  'book': '책',
  'books': '책들',
  'boots': '장화',
  'bored': '심심한',
  'born': '태어난',
  'bother': '귀찮게 하다',
  'bottle': '유리병',
  'bottom': '바닥',
  'bought': '샀다',
  'boulder': '바위',
  'bounce': '통통 튀다',
  'bounced': '튀었다',
  'bowl': '그릇',
  'box': '상자',
  'boxes': '상자들',
  'boy': '남자아이',
  'boys': '남자아이들',
  'bracelets': '팔찌들',
  'brain': '뇌',
  'brains': '뇌',
  'branch': '나뭇가지',
  'brave': '용감한',
  'bread': '빵',
  'break': '부수다',
  'breakfast': '아침밥',
  'breathe': '숨쉬다',
  'breeze': '산들바람',
  'bridge': '다리',
  'bright': '밝은',
  'brightly': '밝게',
  'bring': '가져오다',
  'bringing': '가져오는',
  'brings': '가져온다',
  'broke': '부쉈다',
  'brother': '형제',
  'brothers': '형제들',
  'brought': '가져왔다',
  'brush': '솔',
  'buck': '수사슴',
  'bucket': '양동이',
  'buffalo': '물소',
  'build': '짓다',
  'builder': '짓는 사람',
  'builders': '짓는 사람들',
  'building': '건물',
  'builds': '짓는다',
  'built': '지었다',
  'bull': '황소',
  'bullfrog': '황소개구리',
  'bullied': '괴롭힘당한',
  'bumper': '범퍼',
  'bunch': '한 다발',
  'burn': '불에 타다',
  'burned': '불탔다',
  'burning': '불타는',
  'burns': '불탄다',
  'bus': '버스',
  'bush': '덤불',
  'busy': '바쁜',
  'butterfly': '나비',
  'button': '단추',
  'buy': '사다',
  'buzzing': '윙윙거리는',
  'bye': '잘 가',
  'bye-bye': '안녕',
  // ── c ──
  'cabbages': '양배추들',
  'cake': '케이크',
  'calf': '송아지',
  'call': '부르다',
  'called': '불렀다',
  'calls': '부른다',
  'came': '왔다',
  'camping': '캠핑',
  'cannot': '할 수 없다',
  'cap': '야구 모자',
  'car': '자동차',
  'care': '돌보다',
  'carnivore': '고기 먹는 동물',
  'carried': '옮겼다',
  'carries': '옮긴다',
  'carrot': '당근',
  'carrots': '당근들',
  'carry': '옮기다',
  'carrying': '옮기는',
  'cars': '자동차들',
  'cassava': '뿌리채소',
  'cat': '고양이',
  'catch': '잡다',
  'catches': '잡는다',
  'catfish': '메기',
  'cats': '고양이들',
  'cattle': '소 떼',
  'caught': '잡았다',
  'celebrate': '축하하다',
  'center': '가운데',
  'centre': '가운데',
  'cereal': '시리얼',
  'ceremony': '행사',
  'chains': '사슬',
  'chair': '의자',
  'chairs': '의자들',
  'chalk': '분필',
  'chameleon': '카멜레온',
  'change': '바꾸다',
  'character': '등장인물',
  'charge': '돌진하다',
  'chases': '쫓는다',
  'chasing': '쫓는',
  'check': '살펴보다',
  'cheeks': '볼',
  'cheese': '치즈',
  'chess': '체스',
  'chest': '가슴',
  'chick': '병아리',
  'chicken': '닭',
  'chickens': '닭들',
  'chicks': '병아리들',
  'chief': '족장',
  'child': '아이',
  'children': '아이들',
  'chillies': '고추들',
  'chimpanzee': '침팬지',
  'chin': '턱',
  'chocolates': '초콜릿',
  'choice': '선택',
  'choose': '고르다',
  'chop': '토막 내다',
  'church': '교회',
  'circus': '서커스',
  'city': '도시',
  'class': '우리 반',
  'classroom': '교실',
  'claw': '발톱',
  'clay': '진흙',
  'clean': '깨끗한',
  'clever': '똑똑한',
  'click': '딸깍하다',
  'cliff': '절벽',
  'climb': '오르다',
  'climbs': '오른다',
  'clock': '시계',
  'close': '닫다',
  'closed': '닫혔다',
  'clothes': '옷',
  'cloud': '구름',
  'clouds': '구름들',
  'coach': '코치',
  'coaster': '롤러코스터',
  'coat': '겉옷',
  'coconuts': '코코넛',
  'coffee': '커피',
  'cold': '추운',
  'collect': '모으다',
  'collecting': '모으기',
  'collects': '모은다',
  'color': '색',
  'colored': '색칠한',
  'colour': '색깔',
  'colourful': '알록달록한',
  'colours': '색깔들',
  'comb': '빗',
  'come': '오다',
  'comes': '온다',
  'coming': '오는',
  'comma': '쉼표',
  'community': '마을 사람들',
  'company': '회사',
  'competing': '겨루는',
  'compound': '집터',
  'computer': '컴퓨터',
  'concert': '음악회',
  'coneys': '바위너구리',
  'considered': '생각했다',
  'container': '통',
  'contest': '겨루기',
  'continued': '계속했다',
  'continues': '계속한다',
  'controls': '조종한다',
  'cook': '요리하다',
  'cooked': '요리했다',
  'cookie': '쿠키',
  'cookies': '쿠키들',
  'cooking': '요리하기',
  'cooks': '요리한다',
  'cool': '시원한',
  'cooldrink': '음료수',
  "couldn't": '할 수 없었다',
  'counselled': '타일렀다',
  'counsels': '타이른다',
  'count': '세다',
  'counted': '세었다',
  'country': '나라',
  'couple': '두 사람',
  'cousin': '사촌',
  'covered': '덮었다',
  'cow': '소',
  'cows': '소들',
  'crab': '게',
  'cranes': '두루미들',
  'crashed': '부딪혔다',
  'crawl': '기어가다',
  'crayons': '크레용',
  'crazy': '엉뚱한',
  'cream': '크림',
  'created': '만들었다',
  'creature': '생물',
  'creatures': '생물들',
  'cried': '울었다',
  'cries': '운다',
  'crocodile': '악어',
  'crocodiles': '악어들',
  'crook': '악당',
  'crops': '농작물',
  'cross': '건너다',
  'crow': '까마귀',
  'crowds': '사람 무리',
  'crows': '까마귀들',
  'crunch': '아삭 씹다',
  'crutches': '목발',
  'cry': '울다',
  'crying': '우는',
  'cubs': '새끼들',
  'cunning': '꾀 많은',
  'cupboard': '찬장',
  'cupcakes': '컵케이크',
  'curious': '궁금한',
  'current': '물살',
  'customers': '손님들',
  'cut': '자르다',
  'cute': '귀여운',
  'cuts': '자른다',
  // ── d ──
  'dab': '살짝 두드리다',
  'dad': '아빠',
  'daddy': '아빠',
  'daily': '날마다',
  'dance': '춤',
  'danced': '춤췄다',
  'dancer': '무용수',
  'dancing': '춤추기',
  'dangerous': '위험한',
  'dark': '어두운',
  'darling': '사랑스러운',
  'daughter': '딸',
  'daughters': '딸들',
  'day': '날',
  'days': '날들',
  'deaf': '귀가 안 들리는',
  'dear': '소중한',
  'decided': '정했다',
  'deer': '사슴',
  'delicious': '맛있는',
  'desert': '사막',
  'despite': '그런데도',
  'different': '다른',
  'dig': '파다',
  'dignity': '소중함',
  'dimples': '보조개',
  'dinner': '저녁밥',
  'dinosaur': '공룡',
  'dip': '담그다',
  'dirt': '흙',
  'dirty': '더러운',
  'disciples': '제자들',
  'discussing': '의논하는',
  'distance': '거리',
  'dive': '뛰어들다',
  'doctor': '의사',
  'dog': '개',
  'dogs': '개들',
  'doll': '인형',
  'dolls': '인형들',
  'done': '끝난',
  'donkey': '당나귀',
  'donkeys': '당나귀들',
  'door': '문',
  'dormouse': '겨울잠쥐',
  'dough': '반죽',
  'dove': '비둘기',
  'down': '아래로',
  'downstairs': '아래층',
  'dragon': '용',
  'drama': '연극',
  'draw': '그리다',
  'drawing': '그림',
  'drawings': '그림들',
  'draws': '그린다',
  'dream': '꿈',
  'dreamed': '꿈꿨다',
  'dreaming': '꿈꾸는',
  'dreams': '꿈들',
  'dress': '원피스',
  'dresses': '원피스들',
  'drew': '그렸다',
  'dribbles': '공을 몬다',
  'dried': '말렸다',
  'drink': '마시다',
  'drinking': '마시는',
  'drive': '운전하다',
  'driver': '운전사',
  'driving': '운전하는',
  'drops': '떨어뜨린다',
  'drought': '가뭄',
  'drum': '북',
  'drums': '북들',
  'dry': '마른',
  'duck': '오리',
  'ducks': '오리들',
  'dung': '똥',
  'durian': '두리안',
  // ── e ──
  'eagle': '독수리',
  'ear': '귀',
  'early': '이른',
  'earrings': '귀걸이',
  'ears': '두 귀',
  'earth': '땅',
  'easy': '쉬운',
  'eat': '먹다',
  'eating': '먹는',
  'eats': '먹는다',
  'edge': '가장자리',
  'education': '교육',
  'egg': '달걀',
  'eggs': '달걀들',
  'elder': '어른',
  'elders': '어른들',
  'elephant': '코끼리',
  'elk': '큰사슴',
  'emotions': '감정',
  'end': '끝',
  'ending': '끝나는',
  'energy': '힘',
  'engines': '엔진',
  'enjoy': '즐기다',
  'enjoyed': '즐거웠다',
  'enjoying': '즐기는',
  'enjoys': '즐긴다',
  'enough': '충분한',
  'entered': '들어갔다',
  'entering': '들어가는',
  'escaped': '도망쳤다',
  'even': '심지어',
  'evening': '저녁',
  'event': '일어난 일',
  'eventually': '마침내',
  'everybody': '모두',
  'everyday': '날마다의',
  'everyone': '모든 사람',
  'everything': '모든 것',
  'except': '빼고',
  'excited': '신난',
  'exercise': '운동',
  'expecting': '기다리는',
  'explore': '탐험하다',
  'eyes': '눈',
  // ── f ──
  'face': '얼굴',
  'fair': '공평한',
  'fairy': '요정',
  'fall': '떨어지다',
  'falling': '떨어지는',
  'falls': '떨어진다',
  'family': '가족',
  'famine': '굶주림',
  'famous': '유명한',
  'far': '먼',
  'fare': '차비',
  'farm': '농장',
  'farmer': '농부',
  'fast': '빠른',
  'faster': '더 빠른',
  'fat': '뚱뚱한',
  'father': '아빠',
  'favorite': '가장 좋아하는',
  'favourite': '가장 좋아하는',
  'fawn': '아기 사슴',
  'feather': '깃털',
  'feathers': '깃털들',
  'feed': '먹이다',
  'feel': '느끼다',
  'feeling': '느낌',
  'feelings': '느낌들',
  'feels': '느낀다',
  'feet': '두 발',
  'fell': '넘어졌다',
  'felt': '느꼈다',
  'festive': '축제 같은',
  'fetch': '가지러 가다',
  'few': '몇 개의',
  'fidgets': '꼼지락거린다',
  'field': '들판',
  'fight': '싸우다',
  'figs': '무화과',
  'fill': '채우다',
  'filled': '채웠다',
  'find': '찾다',
  'finished': '끝냈다',
  'fire': '불',
  'fireflies': '반딧불이들',
  'firefly': '반딧불이',
  'firewood': '땔나무',
  'first': '첫 번째',
  'fish': '물고기',
  'fished': '낚시했다',
  'fishermen': '어부들',
  'fishing': '낚시',
  'fit': '맞다',
  'five': '다섯',
  'fix': '고치다',
  'flags': '깃발들',
  'flamingo': '홍학',
  'flamingos': '홍학들',
  'flap': '퍼덕이다',
  'flapped': '퍼덕였다',
  'fleas': '벼룩들',
  'flew': '날았다',
  'flies': '파리들',
  'flight': '비행',
  'flip-flop': '슬리퍼',
  'flooded': '물에 잠겼다',
  'floor': '마루',
  'floppy': '축 늘어진',
  'flour': '밀가루',
  'flower': '꽃',
  'flowers': '꽃들',
  'flute': '피리',
  'fly': '날다',
  'flying': '나는',
  'fog': '안개',
  'fold': '접다',
  'follow': '따라가다',
  'followed': '따라갔다',
  'food': '음식',
  'foolish': '어리석은',
  'foot': '발',
  'football': '축구',
  'footprint': '발자국',
  'forest': '숲',
  'forgot': '잊었다',
  'forms': '모양들',
  'forward': '앞쪽으로',
  'found': '찾았다',
  'four': '넷',
  'fox': '여우',
  'freely': '자유롭게',
  'fried': '튀겼다',
  'friend': '친구',
  'friends': '친구들',
  'friendship': '우정',
  'frightened': '겁먹은',
  'frog': '개구리',
  'front': '앞',
  'fruit': '과일',
  'fruits': '과일들',
  'fruity': '과일 맛의',
  'full': '가득 찬',
  'fun': '재미',
  'fur': '털',
  'further': '더 멀리',
  'future': '미래',
  'fuzzy': '보송보송한',
  // ── g ──
  'game': '놀이',
  'garden': '정원',
  'gate': '대문',
  'gathered': '모았다',
  'gave': '주었다',
  'genet': '사향고양이',
  'genie': '램프 요정',
  'gently': '살살',
  'germs': '세균',
  'get': '얻다',
  'gets': '얻는다',
  'getting': '얻는',
  'gift': '선물',
  'giggle': '킥킥 웃다',
  'giraffe': '기린',
  'giraffes': '기린들',
  'girl': '여자아이',
  'girls': '여자아이들',
  'give': '주다',
  'gives': '준다',
  'glad': '기쁜',
  'glass': '유리',
  'glory': '영광',
  'glow': '빛나다',
  'goal': '골',
  'goat': '염소',
  'goats': '염소들',
  'god': '하느님',
  'gods': '신들',
  'goes': '간다',
  'going': '가는',
  'gold': '금',
  'golden': '황금빛의',
  'gone': '사라진',
  'goo': '끈적이',
  'good': '좋은',
  'goodies': '맛있는 것들',
  'goodnight': '잘 자',
  'goose': '거위',
  'gorilla': '고릴라',
  'got': '얻었다',
  'grams': '그램',
  'granary': '곡식 창고',
  'grandma': '할머니',
  'grannies': '할머니들',
  'granny': '할머니',
  'grape': '포도',
  'grapes': '포도들',
  'grass': '풀',
  'great': '훌륭한',
  'greater': '더 훌륭한',
  'greatest': '가장 훌륭한',
  'green': '초록',
  'greets': '인사한다',
  'grew': '자랐다',
  'grey': '회색',
  'ground': '땅바닥',
  'group': '무리',
  'groups': '무리들',
  'grow': '자라다',
  'grown': '다 자란',
  'grows': '자란다',
  'grumpy': '심술난',
  'guarded': '지켰다',
  'guess': '알아맞히다',
  'gulls': '갈매기들',
  // ── h ──
  'hadedas': '아프리카 새',
  'hair': '머리카락',
  'haircut': '이발',
  'hairpin': '머리핀',
  'half': '반',
  'halwa': '달콤한 과자',
  'hand': '손',
  'handbag': '손가방',
  'hands': '두 손',
  'happen': '일어나다',
  'happened': '일어났다',
  'happily': '행복하게',
  'happy': '행복한',
  'hard': '어려운',
  'hare': '산토끼',
  "hasn't": '없다',
  'hat': '모자',
  'hatched': '알에서 나왔다',
  'hatchlings': '갓 깬 새끼들',
  'hate': '미워하다',
  "he'll": '그가 할 거야',
  'head': '머리',
  'heal': '낫게 하다',
  'healer': '치료하는 사람',
  'hear': '듣다',
  'heard': '들었다',
  'hearing': '듣는',
  'hears': '듣는다',
  'heart': '심장',
  'heaven': '하늘나라',
  'heir': '물려받는 사람',
  'helicopter': '헬리콥터',
  'hello': '안녕하세요',
  'help': '돕다',
  'helped': '도왔다',
  'helper': '도우미',
  'helpful': '도움이 되는',
  'helping': '돕는',
  'helps': '돕는다',
  'hen': '암탉',
  'herd': '짐승 떼',
  'herds': '짐승 떼들',
  'hermit': '혼자 사는 이',
  'hero': '영웅',
  'hide': '숨다',
  'hides': '숨는다',
  'high': '높은',
  'higher': '더 높은',
  'highest': '가장 높은',
  'hill': '언덕',
  'hills': '언덕들',
  'hippos': '하마들',
  'hits': '친다',
  'hoe': '호미',
  'hold': '들고 있다',
  'hole': '구멍',
  'home': '우리 집',
  'homes': '우리 집들',
  'homework': '숙제',
  'honey': '꿀',
  'honor': '명예',
  'honoured': '존경받는',
  'hoof': '발굽',
  'hop': '깡충 뛰다',
  'hope': '바라다',
  'horizon': '지평선',
  'horn': '뿔',
  'horned': '뿔 달린',
  'horns': '뿔들',
  'horse': '말',
  'hospital': '병원',
  'host': '집주인',
  'hot': '뜨거운',
  'house': '집',
  'houses': '집들',
  'human': '사람',
  'humans': '사람들',
  'hungry': '배고픈',
  'hunt': '사냥하다',
  'hunter': '사냥꾼',
  'hurry': '서두르다',
  'hurt': '다치다',
  'husband': '남편',
  'hut': '오두막',
  'huts': '오두막들',
  'hyena': '하이에나',
  'hyenas': '하이에나들',
  // ── i ──
  "i'll": '내가 할 거야',
  'ice': '얼음',
  'icing': '설탕 크림',
  'icy': '얼음처럼 찬',
  'idea': '생각',
  'illness': '병',
  'imagine': '상상하다',
  'importance': '중요함',
  'important': '중요한',
  'injection': '주사',
  'insects': '벌레들',
  'inside': '안에',
  'inspire': '힘을 주다',
  'instep': '발등',
  'instrument': '악기',
  'invasion': '쳐들어옴',
  'invisible': '보이지 않는',
  'invite': '초대하다',
  'invited': '초대했다',
  'iron': '쇠',
  // ── j ──
  'jackal': '자칼',
  'jacket': '웃옷',
  'jackets': '외투',
  'jar': '항아리',
  'jelly': '젤리',
  'jersey': '운동복',
  'jerseys': '운동복들',
  'jet': '제트기',
  'jig': '신나는 춤',
  'jiggle': '흔들다',
  'job': '일',
  'join': '함께하다',
  'joins': '함께한다',
  'joke': '농담',
  'journey': '여행',
  'joy': '기쁨',
  'judge': '판사',
  'juice': '주스',
  'jump': '뛰다',
  'jumped': '뛰었다',
  'jumps': '뛴다',
  'jungle': '정글',
  'junior': '어린',
  'justice': '정의',
  // ── k ──
  'keep': '지키다',
  'keeps': '지킨다',
  'key': '열쇠',
  'kick': '차다',
  'kids': '꼬마들',
  'king': '왕',
  'kingdom': '왕국',
  'kitchen': '부엌',
  'kite': '연',
  'kitten': '새끼 고양이',
  'kittens': '새끼 고양이들',
  'knees': '무릎',
  'knew': '알았다',
  'knock': '똑똑 두드리다',
  'know': '알다',
  'knows': '안다',
  // ── l ──
  'lack': '모자람',
  'ladies': '여자분들',
  'lady': '여자분',
  'ladybirds': '무당벌레들',
  'lake': '호수',
  'lakeside': '호숫가',
  'lambs': '새끼 양들',
  'land': '땅덩어리',
  'language': '나라 말',
  'last': '마지막',
  'late': '늦은',
  'laugh': '웃다',
  'laughed': '웃었다',
  'laughter': '웃음',
  'lay': '누웠다',
  'lazy': '게으른',
  'leader': '대장',
  'leads': '이끈다',
  'leaf': '나뭇잎',
  'leafy': '잎이 많은',
  'learn': '배우다',
  'learning': '배우는',
  'learnt': '배웠다',
  'least': '가장 적은',
  'leave': '떠나다',
  'leaves': '나뭇잎들',
  'left': '왼쪽',
  'legs': '다리들',
  'leopard': '표범',
  'less': '더 적은',
  'let': '하게 하다',
  'letter': '편지',
  'letters': '글자들',
  'library': '도서관',
  'life': '삶',
  'lifeguards': '안전 요원들',
  'lifejacket': '구명조끼',
  'lift': '들어올리다',
  'lifted': '들어올렸다',
  'light': '빛',
  'lightning': '번개',
  'lights': '불빛들',
  'like': '좋아하다',
  'liked': '좋아했다',
  'likes': '좋아한다',
  'line': '줄',
  'lines': '줄들',
  'lion': '사자',
  'lioness': '암사자',
  'lions': '사자들',
  'list': '목록',
  'listen': '귀 기울이다',
  'litre': '리터',
  'little': '작은',
  'live': '살다',
  'lived': '살았다',
  'lives': '산다',
  'living': '사는',
  'lizard': '도마뱀',
  'lonely': '외로운',
  'long': '긴',
  'longer': '더 긴',
  'look': '쳐다보다',
  'looked': '쳐다봤다',
  'looking': '쳐다보는',
  'looks': '쳐다본다',
  'loses': '잃는다',
  'lost': '잃어버린',
  'lot': '많이',
  'lots': '아주 많이',
  'loud': '시끄러운',
  'louse': '머릿니',
  'love': '사랑하다',
  'loved': '사랑했다',
  'lovely': '아주 예쁜',
  'loves': '사랑한다',
  'low': '낮은',
  'lunch': '점심밥',
  'lush': '푸르른',
  // ── m ──
  'mad': '몹시 화난',
  'made': '만들었다',
  'magic': '마법',
  'magical': '마법 같은',
  'magician': '마술사',
  'maize': '옥수수',
  'make': '만들다',
  'makes': '만든다',
  'making': '만드는',
  'mama': '엄마',
  'man': '남자',
  'manger': '여물통',
  'mango': '망고',
  'mangoes': '망고들',
  'many': '많은',
  'mark': '표시',
  'market': '장터',
  'master': '주인님',
  'mat': '돗자리',
  'matching': '짝이 맞는',
  'materials': '재료들',
  'maybe': '아마도',
  'mealie': '옥수수 알',
  'meals': '밥',
  'means': '뜻한다',
  'meant': '뜻했다',
  'meat': '고기',
  'medal': '메달',
  'medicine': '약',
  'meerkat': '미어캣',
  'meerkats': '미어캣들',
  'meet': '만나다',
  'meeting': '모임',
  'melted': '녹았다',
  'members': '식구들',
  'men': '남자들',
  'mermaid': '인어',
  'message': '소식',
  'met': '만났다',
  'mice': '쥐들',
  'middle': '한가운데',
  'milk': '우유',
  'mine': '내 것',
  'mingling': '어울리는',
  'minutes': '분',
  'mirror': '거울',
  'miss': '그리워하다',
  'missing': '없어진',
  'mix': '섞다',
  'mixes': '섞는다',
  'mom': '엄마',
  'mommy': '엄마',
  'monastery': '절',
  'money': '돈',
  'monkey': '원숭이',
  'monkeys': '원숭이들',
  'monks': '스님들',
  'monster': '괴물',
  'month': '한 달',
  'months': '여러 달',
  'moon': '달',
  'morning': '아침',
  'mosquito': '모기',
  'mother': '엄마',
  'mothers': '엄마들',
  'motorbike': '오토바이',
  'mountain': '산',
  'mouse': '쥐',
  'mouth': '입',
  'move': '움직이다',
  'moved': '움직였다',
  'moving': '움직이는',
  'much': '아주 많은',
  'mucky': '지저분한',
  'mud': '진흙탕',
  'mum': '엄마',
  'mummy': '엄마',
  'munch': '우물우물 먹다',
  'music': '음악',
  'musical': '음악의',
  // ── n ──
  'name': '이름',
  'named': '이름 붙였다',
  'nap': '낮잠',
  'naughty': '장난꾸러기',
  'near': '가까운',
  'nearby': '가까이에',
  'neck': '목',
  'necklace': '목걸이',
  'need': '필요하다',
  'needle': '바늘',
  'neighbour': '이웃',
  'neighbours': '이웃들',
  'nervous': '긴장한',
  'nest': '둥지',
  'net': '그물',
  'netball': '네트볼',
  'nets': '그물들',
  'new': '새로운',
  'next': '다음',
  'nice': '친절한',
  'night': '밤',
  'nine': '아홉',
  'ninety': '아흔',
  'noise': '소리',
  'noisy': '소란스러운',
  'nose': '코',
  'noses': '코들',
  'nothing': '아무것도',
  'numbers': '숫자들',
  'nurse': '간호사',
  // ── o ──
  "o'clock": '정각',
  'oakum': '왕펭귄 새끼',
  'oar': '노',
  'oatmeal': '오트밀',
  'occasions': '특별한 날들',
  'ocean': '큰 바다',
  'off': '떨어져',
  'officers': '경찰관들',
  'ogre': '도깨비',
  'okay': '괜찮은',
  'old': '나이 많은',
  'older': '더 나이 든',
  'one': '하나',
  'ones': '것들',
  'open': '열다',
  'opens': '연다',
  'opposite': '반대의',
  'orange': '주황',
  'orchard': '과수원',
  'orders': '시킨다',
  'others': '다른 사람들',
  'out': '밖으로',
  'outside': '바깥',
  'oval': '타원',
  'over': '위로',
  'owl': '부엉이',
  'owner': '주인',
  'oxygen': '산소',
  // ── p ──
  'packed': '쌌다',
  'paid': '냈다',
  'pain': '아픔',
  'paint': '물감',
  'painted': '색칠했다',
  'painter': '화가',
  'paints': '물감들',
  'palace': '궁전',
  'palm': '손바닥',
  'pancake': '팬케이크',
  'pancakes': '팬케이크들',
  'pants': '바지',
  'paper': '종이',
  'parable': '옛이야기',
  'parcel': '소포',
  'parents': '부모님',
  'park': '공원',
  'part': '부분',
  'party': '파티',
  'pass': '지나가다',
  'past': '지난날',
  'pastures': '풀밭',
  'path': '오솔길',
  'paw': '앞발',
  'pawn': '졸',
  'pay': '돈을 내다',
  'paying': '돈을 내는',
  'peace': '평화',
  'peacock': '공작새',
  'pear': '배',
  'peas': '완두콩',
  'pebbles': '조약돌들',
  'pedal': '페달',
  'pen': '펜',
  'pencil': '연필',
  'pencils': '연필들',
  'penguins': '펭귄들',
  'people': '사람들',
  'perfect': '완벽한',
  'perhaps': '아마',
  'person': '한 사람',
  'persuaded': '설득했다',
  'pests': '해충들',
  'pet': '반려동물',
  'petals': '꽃잎들',
  'phone': '전화',
  'pick': '집다',
  'picked': '집었다',
  'pickers': '따는 사람들',
  'picnic': '소풍',
  'picture': '그림',
  'pictures': '그림들',
  'pie': '파이',
  'piece': '조각',
  'pieces': '조각들',
  'pig': '돼지',
  'pigeons': '비둘기들',
  'pigs': '돼지들',
  'pilgrimage': '순례',
  'pillow': '베개',
  'pink': '분홍',
  'pitcher': '물병',
  'pizza': '피자',
  'place': '곳',
  'plains': '넓은 들',
  'plan': '계획',
  'planet': '행성',
  'plant': '식물',
  'planted': '심었다',
  'plants': '식물들',
  'plastic': '플라스틱',
  'play': '놀다',
  'played': '놀았다',
  'players': '선수들',
  'playful': '장난스러운',
  'playing': '노는',
  'plays': '논다',
  'please': '부디',
  'pluck': '뜯다',
  'pods': '꼬투리',
  'point': '가리키다',
  'points': '가리킨다',
  'police': '경찰',
  'polite': '예의 바른',
  'politely': '예의 바르게',
  'pollen': '꽃가루',
  'pond': '연못',
  'ponds': '연못들',
  'poo': '응가',
  'pool': '수영장',
  'poor': '가난한',
  'popular': '인기 있는',
  'porridge': '죽',
  'positive': '긍정적인',
  'possible': '할 수 있는',
  'post': '기둥',
  'posters': '포스터들',
  'postman': '우편배달부',
  'pot': '냄비',
  'potatoes': '감자들',
  'pounding': '빻는',
  'poured': '부었다',
  'pours': '붓는다',
  'power': '큰 힘',
  'practise': '연습하다',
  'prepare': '준비하다',
  'prepared': '준비했다',
  'present': '선물',
  'pretends': '흉내 낸다',
  'pretty': '예쁜',
  'price': '값',
  'pride': '자랑스러움',
  'primary': '초등의',
  'prince': '왕자',
  'princess': '공주',
  'principal': '교장 선생님',
  'print': '찍다',
  'prints': '자국들',
  'problem': '문제',
  'problems': '문제들',
  'process': '과정',
  'produce': '만들어내다',
  'produced': '만들어냈다',
  'project': '과제',
  'promised': '약속했다',
  'provide': '마련해 주다',
  'puddle': '물웅덩이',
  'pulled': '당겼다',
  'pumpkin': '호박',
  'pupils': '학생들',
  'puppy': '강아지',
  'purple': '보라',
  'pushed': '밀었다',
  'put': '놓다',
  'puts': '놓는다',
  // ── q ──
  'queen': '여왕',
  'quick': '재빠른',
  'quiet': '조용한',
  'quietly': '조용히',
  // ── r ──
  'rabbit': '토끼',
  'rabbits': '토끼들',
  'race': '달리기 시합',
  'racing': '달리는',
  'radio': '라디오',
  'rain': '비',
  'rainbow': '무지개',
  'rainbows': '무지개들',
  'raining': '비 오는',
  'raised': '길렀다',
  'ran': '달렸다',
  'rap': '랩',
  'rat': '큰 쥐',
  'rats': '큰 쥐들',
  'ravens': '큰 까마귀들',
  'reach': '닿다',
  'reached': '닿았다',
  'read': '읽다',
  'reading': '읽기',
  'ready': '준비된',
  'real': '진짜의',
  'really': '정말',
  'recycled': '다시 쓴',
  'red': '빨강',
  'refreshing': '상쾌한',
  'remember': '기억하다',
  'remove': '치우다',
  'replied': '대꾸했다',
  'replies': '대꾸한다',
  'rescue': '구하다',
  'respects': '존중한다',
  'responds': '대답한다',
  'rest': '쉬다',
  'results': '결과',
  'rice': '쌀',
  'rich': '부자인',
  'rid': '없애다',
  'ride': '타다',
  'right': '오른쪽',
  'ring': '반지',
  'rings': '반지들',
  'rip': '찢다',
  'ripe': '잘 익은',
  'rising': '떠오르는',
  'river': '강',
  'rivers': '강들',
  'road': '길',
  'roars': '으르렁댄다',
  'robot': '로봇',
  'rock': '큰 돌',
  'rods': '낚싯대',
  'roof': '지붕',
  'room': '방',
  'rooster': '수탉',
  'roosters': '수탉들',
  'root': '뿌리',
  'rope': '밧줄',
  'round': '둥근',
  'row': '노 젓다',
  'rowers': '노 젓는 사람들',
  'rubbish': '쓰레기',
  'rude': '버릇없는',
  'rule': '규칙',
  'rules': '규칙들',
  'run': '달리다',
  'running': '뛰는',
  'runs': '달린다',
  'rushes': '서두른다',
  // ── s ──
  'sad': '슬픈',
  'safe': '안전한',
  'said': '말했다',
  'salt': '소금',
  'salty': '짠',
  'samoosas': '삼각 튀김',
  'sand': '모래',
  'sandbox': '모래놀이터',
  'sang': '노래했다',
  'sat': '앉았다',
  'sausage': '소시지',
  'saved': '구했다',
  'saw': '봤다',
  'say': '말하다',
  'saying': '말하는',
  'says': '말한다',
  'scarce': '모자란',
  'scared': '무서워하는',
  'scarf': '목도리',
  'scarfs': '목도리들',
  'school': '학교',
  'scored': '골을 넣었다',
  'scouts': '스카우트',
  'scrambled': '휘저어 익힌',
  'screamed': '비명 질렀다',
  'screaming': '비명 지르는',
  'screams': '비명 지른다',
  'sea': '바다',
  'seal': '물개',
  'search': '찾아보다',
  'searched': '찾아봤다',
  'season': '계절',
  'seat': '자리',
  'seconds': '초',
  'secret': '비밀',
  'see': '보다',
  'see-saw': '시소',
  'seed': '씨앗',
  'seedling': '새싹',
  'seeds': '씨앗들',
  'seek': '찾아 나서다',
  'seen': '본',
  'sees': '본다',
  'selfish': '이기적인',
  'sell': '팔다',
  'sells': '판다',
  'senses': '감각',
  'sent': '보냈다',
  'sentence': '문장',
  'served': '차려 줬다',
  'set': '차려 놓다',
  'seven': '일곱',
  'several': '여러',
  'shadow': '그림자',
  'shake': '마구 흔들다',
  'shapes': '모양',
  'share': '나누다',
  'sharing': '나누기',
  'shark': '상어',
  'sharp': '뾰족한',
  'shed': '창고',
  'sheep': '양',
  'shell': '껍데기',
  'shells': '껍데기들',
  'shepherd': '양치기',
  'shepherds': '양치기들',
  'shines': '빛난다',
  'shiny': '반짝이는',
  'shirt': '셔츠',
  'shoe': '신발',
  'shoes': '신발들',
  'shop': '가게',
  'shopping': '장보기',
  'shops': '가게들',
  'shore': '물가',
  'shores': '물가들',
  'short': '짧은',
  'shout': '소리치다',
  'shouted': '소리쳤다',
  'shouts': '소리친다',
  'show': '보여주다',
  'shy': '부끄러운',
  'siblings': '형제자매',
  'sick': '아픈',
  'side': '옆',
  'sign': '표지판',
  'signal': '신호',
  'signs': '표지판들',
  'silly': '우스꽝스러운',
  'since': '그때부터',
  'sing': '노래하다',
  'singing': '노래하기',
  'single': '하나의',
  'sings': '노래한다',
  'sister': '자매',
  'sisters': '자매들',
  'sit': '앉다',
  'sits': '앉는다',
  'sitting': '앉아 있는',
  'six': '여섯',
  'size': '크기',
  'skeleton': '뼈대',
  'skin': '살갗',
  'skipping': '줄넘기',
  'sky': '하늘',
  'slate': '작은 칠판',
  'sleep': '자다',
  'sleeping': '자는',
  'sleeps': '잔다',
  'slice': '얇은 조각',
  'slices': '얇은 조각들',
  'slide': '미끄럼틀',
  'slipped': '미끄러졌다',
  'slow': '느린',
  'slowly': '천천히',
  'small': '조그만',
  'smell': '냄새',
  'smelling': '냄새 맡는',
  'smells': '냄새 난다',
  'smelly': '냄새 나는',
  'smile': '미소',
  'smiled': '미소 지었다',
  'smiles': '미소 짓는다',
  'smiling': '미소 짓는',
  'smoke': '연기',
  'snacks': '간식',
  'snail': '달팽이',
  'snake': '뱀',
  'snow': '흰 눈',
  'soap': '비누',
  'soared': '높이 날았다',
  'sob': '흐느끼다',
  'soccer': '축구 경기',
  'sock': '양말',
  'socks': '양말들',
  'sofa': '소파',
  'soft': '부드러운',
  'soil': '기름진 흙',
  'sold': '팔았다',
  'someone': '누군가',
  'something': '무언가',
  'sometimes': '가끔',
  'son': '아들',
  'son-in-law': '사위',
  'song': '노래',
  'songs': '노래들',
  'sons': '아들들',
  'soon': '곧',
  'sore': '쓰라린',
  'soul': '영혼',
  'sound': '들리는 소리',
  'soup': '국',
  'space': '우주',
  'sparrows': '참새들',
  'speak': '말을 하다',
  'special': '특별한',
  'spectacles': '안경',
  'spend': '쓰다',
  'spent': '썼다',
  'spices': '양념',
  'spin': '빙글 돌다',
  'spinach': '시금치',
  'spirit': '정신',
  'splashed': '첨벙거렸다',
  'splendid': '아주 멋진',
  'splits': '쪼갠다',
  'sports': '운동 경기',
  'spot': '점',
  'spots': '점들',
  'spring': '봄',
  'springs': '샘물',
  'squirrel': '다람쥐',
  'squirrels': '다람쥐들',
  'stained': '얼룩진',
  'stand': '서다',
  'standing': '서 있는',
  'stare': '빤히 보다',
  'staring': '빤히 보는',
  'stars': '별들',
  'start': '시작하다',
  'started': '시작했다',
  'station': '역',
  'stay': '머무르다',
  'staying': '머무르는',
  'step': '걸음',
  'stepped': '걸어갔다',
  'steps': '계단',
  'stick': '막대기',
  'sticks': '막대기들',
  'stilts': '죽마',
  'stinging': '쏘는',
  'stoep': '툇마루',
  'stone': '돌',
  'stones': '돌멩이',
  'stop': '멈추다',
  'stopped': '멈췄다',
  'store': '큰 가게',
  'stories': '이야기들',
  'storm': '폭풍',
  'story': '이야기',
  'storybook': '이야기책',
  'storybooks': '이야기책들',
  'stranger': '낯선 사람',
  'stream': '시냇물',
  'street': '길거리',
  'stretched': '쭉 폈다',
  'strikes': '세게 친다',
  'stripes': '줄무늬',
  'stroking': '쓰다듬는',
  'strong': '힘센',
  'stronger': '더 힘센',
  'strongest': '가장 센',
  'strutted': '으스대며 걸었다',
  'stuck': '달라붙은',
  'students': '학생',
  'studies': '공부한다',
  'style': '멋',
  'suddenly': '갑자기',
  'sugar': '설탕',
  'sugarcane': '사탕수수',
  'suitcase': '여행 가방',
  'summer': '여름',
  'sun': '해',
  'sunflower': '해바라기',
  'sunflowers': '해바라기들',
  'sunrise': '해돋이',
  'super': '대단한',
  'superhero': '초능력 영웅',
  'supper': '늦은 저녁밥',
  'supposed': '해야 하는',
  'surface': '겉면',
  'surprise': '놀람',
  'swallow': '삼키다',
  'swam': '헤엄쳤다',
  'sweet': '달콤한',
  'sweetest': '가장 달콤한',
  'sweets': '사탕',
  'swept': '쓸었다',
  'swim': '헤엄치다',
  'swimming': '헤엄치는',
  'swing': '그네',
  'swinging': '그네 타는',
  'syrup': '시럽',
  // ── t ──
  't-shirt': '티셔츠',
  'ta-ta': '잘 가',
  'table': '탁자',
  'tables': '탁자들',
  'tail': '꼬리',
  'tailor': '재단사',
  'tailoring': '옷 만들기',
  'tails': '꼬리들',
  'take': '가져가다',
  'takes': '가져간다',
  'taking': '가져가는',
  'talk': '이야기하다',
  'talked': '이야기했다',
  'talking': '이야기하는',
  'talks': '이야기한다',
  'tall': '키 큰',
  'tamer': '길들이는 사람',
  'tap': '수도꼭지',
  'taste': '맛',
  'tastes': '맛본다',
  'taught': '가르쳤다',
  'tax': '세금',
  'taxi': '택시',
  'tea': '차',
  'teacher': '선생님',
  'teachers': '선생님들',
  'teaches': '가르친다',
  'teaching': '가르치는',
  'team': '팀',
  'teammates': '팀 친구들',
  'tears': '눈물',
  'teeth': '이빨',
  'teff': '곡식',
  'tell': '말해주다',
  'tells': '말해준다',
  'ten': '열',
  'tennis': '테니스',
  'tent': '텐트',
  'tentacles': '촉수',
  'term': '학기',
  'test': '시험',
  'thank': '고마워하다',
  'thatch': '초가지붕',
  'thief': '도둑',
  'thieves': '도둑들',
  'thin': '얇은',
  'thing': '물건',
  'things': '물건들',
  'think': '생각하다',
  'thinking': '생각하는',
  'thinks': '생각한다',
  'thirst': '목마름',
  'thirsty': '목마른',
  'thought': '생각했다',
  'thousand': '천',
  'threatened': '위협했다',
  'three': '셋',
  'throne': '왕좌',
  'throw': '던지다',
  'throws': '던진다',
  'thunder': '천둥',
  'tickle': '간지럽히다',
  'tidy': '깔끔한',
  'tied': '묶었다',
  'tiger': '호랑이',
  'tigress': '암호랑이',
  'time': '시간',
  'tins': '깡통들',
  'tiny': '아주 작은',
  'tip': '맨 끝',
  'tired': '피곤한',
  'tissue': '휴지',
  'toast': '토스트',
  'today': '오늘',
  'toes': '발가락',
  'toffee': '쫀득 사탕',
  'together': '함께',
  'told': '말해줬다',
  'tomatoes': '토마토',
  'tomorrow': '내일',
  'tongue': '혀',
  'took': '가져갔다',
  'tooth': '이',
  'top': '꼭대기',
  'tornado': '회오리바람',
  'tortoise': '거북',
  'touch': '만지다',
  'town': '작은 도시',
  'toys': '장난감',
  'trading': '사고팔기',
  'train': '기차',
  'trap': '덫',
  'trapped': '갇힌',
  'travelling': '여행하는',
  'tray': '쟁반',
  'treasure': '보물',
  'tree': '나무',
  'trees': '나무들',
  'triangle': '세모',
  'trickster': '꾀보',
  'tried': '애썼다',
  'tries': '애쓴다',
  'trip': '나들이',
  'trousers': '긴 바지',
  'truck': '트럭',
  'trunk': '코끼리 코',
  'trusty': '믿음직한',
  'truth': '진실',
  'try': '애쓰다',
  'turn': '돌다',
  'turned': '돌았다',
  'turns': '돈다',
  'turtle': '바다거북',
  'twilight': '어스름',
  'twins': '쌍둥이',
  'twists': '비튼다',
  'twittering': '지저귀는',
  'two': '둘',
  'types': '종류',
  // ── u ──
  'umbrella': '우산',
  'umbrellas': '우산들',
  'uncle': '삼촌',
  'under': '아래에',
  'underwear': '속옷',
  'unhappy': '기분 나쁜',
  'uniforms': '교복',
  'unit': '단위',
  'upon': '위에',
  'upside': '거꾸로',
  'use': '사용하다',
  'used': '사용했다',
  'uses': '사용한다',
  'using': '사용하는',
  'usually': '보통',
  'utensils': '그릇들',
  // ── v ──
  'vapour': '수증기',
  'vegetable': '채소',
  'vegetables': '채소들',
  'vehicle': '탈것',
  'veil': '면사포',
  'vest': '조끼',
  'village': '마을',
  'villagers': '동네 사람들',
  'villain': '나쁜 사람',
  'vines': '덩굴',
  'visit': '찾아가다',
  'visited': '찾아갔다',
  'visitors': '찾아온 사람들',
  'voice': '목소리',
  'vulture': '대머리수리',
  // ── w ──
  'waist': '허리',
  'wait': '기다리다',
  'waiter': '종업원',
  'waiting': '기다리고 있는',
  'wake': '깨다',
  'wakes': '깬다',
  'waking': '깨는',
  'walk': '걷다',
  'walked': '걸었다',
  'walking': '걷는',
  'wall': '벽',
  'want': '원하다',
  'wanted': '원했다',
  'wants': '원한다',
  'warm': '따뜻한',
  'warmth': '따뜻함',
  'warthog': '혹멧돼지',
  'wash': '씻다',
  'washed': '씻었다',
  'washes': '씻는다',
  "wasn't": '아니었다',
  'watch': '지켜보다',
  'water': '물',
  'watermelon': '수박',
  'wave': '파도',
  'waves': '파도들',
  'waving': '손 흔드는',
  'wax': '밀랍',
  'way': '가는 길',
  "we're": '우리는',
  "we've": '우리가 했다',
  'wealth': '재산',
  'wear': '입다',
  'wears': '입는다',
  'weather': '날씨',
  'wedding': '결혼식',
  'week': '주',
  'weighs': '무게가 나간다',
  'weird': '이상한',
  'well': '우물',
  'went': '갔다',
  'whenever': '언제든지',
  'wherever': '어디든지',
  'whip': '채찍',
  'white': '하양',
  'whizzed': '쌩 지나갔다',
  'whole': '전체의',
  'widow': '홀어머니',
  'wife': '아내',
  'wig': '가발',
  'wiggle': '꼼지락거리다',
  'wiggly': '꼬불꼬불한',
  'wild': '야생의',
  'win': '이기다',
  'wind': '바람',
  'window': '창문',
  'windowsill': '창턱',
  'wing': '날개',
  'wings': '날개들',
  'winning': '이기는',
  'winter': '겨울',
  'wiped': '닦았다',
  'wisdom': '지혜',
  'wise': '지혜로운',
  'wish': '소원',
  'wished': '소원 빌었다',
  'within': '이내에',
  'wives': '아내들',
  'wizard': '마법사',
  'woke': '깼다',
  'wolf': '늑대',
  'wolves': '늑대들',
  'woman': '여자',
  'women': '여자들',
  'won': '이겼다',
  'wonder': '궁금해하다',
  'wonderful': '멋진',
  'wondering': '궁금해하는',
  'wonky': '삐뚤어진',
  'wood': '나무토막',
  'wool': '양털',
  'word': '낱말',
  'words': '낱말들',
  'work': '일하다',
  'worked': '일했다',
  'workers': '일꾼들',
  'working': '일하는',
  'works': '일한다',
  'workshop': '작업실',
  'world': '세상',
  'worm': '지렁이',
  'worms': '지렁이들',
  'worried': '걱정했다',
  'worry': '걱정하다',
  'wrapper': '포장지',
  'wriggle': '꿈틀거리다',
  'writing': '글쓰기',
  // ── y ──
  'yam': '참마',
  'yams': '참마들',
  'yard': '마당',
  'year': '한 해',
  'years': '여러 해',
  'yellow': '노랑',
  'yes': '그래',
  "you're": '너는',
  "you've": '너가 했다',
  'young': '젊은',
  'younger': '더 어린',
  'youngest': '가장 어린',
  'yours': '네 것',
  'yummy': '아주 맛있는',
  // ── z ──
  'zebra': '얼룩말',
  'zebras': '얼룩말들',
  'zoo': '동물원',
  'zoomed': '쌩 달렸다',
};

/** 등재 개수 — 검증 스크립트와 ADR 기재 수치를 코드로 확인 가능하게 노출한다. */
export const KO_MEANING_COUNT = Object.keys(KO_MEANINGS).length;
